# Nombre del microservicio
spring.application.name=ms-envios

# Puerto del microservicio Envíos
# Inventario 8081, Pedidos 8082, Usuarios 8084 → Envíos usa 8085
server.port=8085

# Cargar variables desde archivo .env
spring.config.import=optional:file:.env[.properties]

# Configuración de Base de Datos MySQL
spring.datasource.url=jdbc:mysql://${DB_HOST_ENVIOS:localhost}:${DB_PORT_ENVIOS:3306}/${DB_NAME_ENVIOS:db_smartlogix_envios}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER_ENVIOS:root}
spring.datasource.password=${DB_PASS_ENVIOS:}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
springdoc.swagger-ui.path=/swagger-ui.html
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.smartlogix=DEBUG

logging.file.name=logs/msEnvios.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

# ===============================
# EUREKA CLIENT
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
# ===============================
# KEYCLOAK / OAuth2 Resource Server
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/smartlogix
