services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: smartlogix-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - smartlogix-net

  eureka:
    build: ./Backend/smartlogix-parent/Eureka
    container_name: smartlogix-eureka
    ports:
      - "8761:8761"
    networks:
      - smartlogix-net

  ms-inventario:
    build: ./Backend/smartlogix-parent/Inventario
    container_name: smartlogix-inventario
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=mysql-inventario
      - DB_PORT=3306
      - DB_NAME=smartlogix_inventario
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - eureka
      - keycloak
    networks:
      - smartlogix-net

  ms-pedidos:
    build: ./Backend/smartlogix-parent/Pedidos
    container_name: smartlogix-pedidos
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - keycloak
      - ms-inventario
    networks:
      - smartlogix-net

  ms-envios:
    build: ./Backend/smartlogix-parent/msEnvios
    container_name: smartlogix-envios
    ports:
      - "8085:8085"
    depends_on:
      - eureka
      - keycloak
    networks:
      - smartlogix-net

  bff:
    build: ./Backend/smartlogix-parent/BFF
    container_name: smartlogix-bff
    ports:
      - "8083:8083"
    environment:
      - INVENTARIO_URL=http://ms-inventario:8081/api/inventario/productos
      - PEDIDOS_URL=http://ms-pedidos:8082/api/pedidos
      - ENVIOS_URL=http://ms-envios:8085/api/envios
      - KEYCLOAK_ISSUER_URI=http://localhost:8080/realms/smartlogix
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/smartlogix/protocol/openid-connect/certs
    depends_on:
      - eureka
      - keycloak
      - ms-inventario
      - ms-pedidos
      - ms-envios
    networks:
      - smartlogix-net

  ms-usuarios:
    build: ./Backend/smartlogix-parent/Usuarios
    container_name: smartlogix-usuarios
    ports:
      - "8084:8084"
    depends_on:
      - eureka
      - keycloak
    networks:
      - smartlogix-net

networks:
  smartlogix-net:
    driver: bridge