spring.application.name=msPedidos
server.port=8082

spring.datasource.url=jdbc:mysql://${DB_HOST_PEDIDOS:localhost}:${DB_PORT_PEDIDOS:3306}/${DB_NAME_PEDIDOS:db_smartlogix_pedidos}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER_PEDIDOS:root}
spring.datasource.password=${DB_PASS_PEDIDOS:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

servicios.inventario.url=${INVENTARIO_URL:http://localhost:8081/api/inventario/productos}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
springdoc.swagger-ui.path=/swagger-ui.html
