spring.application.name=bff-smartlogix
server.port=8083

# URLs de microservicios
servicios.inventario.url=${INVENTARIO_URL:http://localhost:8081/api/inventario/productos}
servicios.pedidos.url=${PEDIDOS_URL:http://localhost:8082/api/pedidos}
servicios.envios.url=${ENVIOS_URL:http://localhost:8085/api/envios}

# Eureka
# Si no tienes Eureka levantado, el BFF igual puede iniciar.
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Actuator / Swagger
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
springdoc.swagger-ui.path=/swagger-ui.html

# Logs
logging.level.root=INFO
logging.level.com.smartlogix=DEBUG
logging.file.name=logs/bffSmartlogix.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
