# ===============================
# NOMBRE DEL MICROSERVICIO
# ===============================
spring.application.name=ms-usuarios

# ===============================
# PUERTO
# ===============================
server.port=8084

# ===============================
# VARIABLES .ENV
# ===============================
spring.config.import=optional:file:.env[.properties]

# ===============================
# BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:mysql://${DB_HOST_USUARIOS:localhost}:${DB_PORT_USUARIOS:3306}/${DB_NAME_USUARIOS:db_smartlogix_usuarios}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER_USUARIOS:root}
spring.datasource.password=${DB_PASS_USUARIOS:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================
# SWAGGER
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.smartlogix=DEBUG

logging.file.name=logs/msUsuarios.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
# ===============================
# EUREKA CLIENT
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
# ===============================
# KEYCLOAK / OAuth2 Resource Server
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/smartlogix
