spring.application.name=eureka-server
server.port=8761

# Eureka Server no se registra a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# URL interna del servidor Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Evita errores por nombre de host en local
eureka.instance.hostname=localhost

# Logs
logging.level.root=INFO
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always