server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # React Router - serve index.html for all routes
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy a microservicios (en producción con Docker)
    location /api/inventario/ {
        proxy_pass http://ms-inventario:8081/api/inventario/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/pedidos {
        proxy_pass http://ms-pedidos:8082/api/pedidos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/envios {
        proxy_pass http://ms-envios:8083/api/envios;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/usuarios {
        proxy_pass http://ms-usuarios:8084/api/usuarios;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
